# Generated by Django 5.1.6 on 2025-02-13 17:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOIDC",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sub",
                    models.CharField(
                        blank=True,
                        help_text="Required. 255 characters or fewer. Letters, numbers, and @/./+/-/_/: characters only.",
                        max_length=255,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid sub. This value may contain only letters, numbers, and @/./+/-/_/: characters.",
                                regex="^[\\w.@+-:]+\\Z",
                            )
                        ],
                        verbose_name="sub",
                    ),
                ),
                ("siret", models.CharField(blank=True, max_length=14, verbose_name="SIRET")),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
    ]
