# Generated by Django 5.1.6 on 2025-02-18 16:26

import django.core.validators
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proconnect", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhitelistedEmailDomain",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "domain",
                    models.CharField(
                        help_text="Required. 255 characters or fewer. Needs to be a valid domain name.",
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.DomainNameValidator()],
                        verbose_name="domain name",
                    ),
                ),
            ],
            options={
                "verbose_name": "whitelisted email domain",
                "verbose_name_plural": "whitelisted email domains",
                "ordering": ["domain"],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
