# Generated by Django 5.0.8 on 2024-08-23 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content_manager", "0038_alter_contentpage_body"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cmsdsfrconfig",
            old_name="notice",
            new_name="notice_title",
        ),
    ]
