# Generated by Django 5.0.8 on 2024-08-30 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content_manager", "0042_alter_contentpage_body"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnalyticsSettings",
            new_name="CustomScriptsSettings",
        ),
    ]
