# Generated by Django 5.1.1 on 2024-09-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_content_manager", "0046_alter_contentpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpage",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="For imported pages, to allow updates.", null=True, verbose_name="Source URL"
            ),
        ),
    ]
