# Generated by Django 5.0.7 on 2024-07-17 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventsindexpage",
            name="filter_by_author",
            field=models.BooleanField(default=False, verbose_name="Filter by author"),
        ),
        migrations.AddField(
            model_name="eventsindexpage",
            name="filter_by_category",
            field=models.BooleanField(default=True, verbose_name="Filter by category"),
        ),
        migrations.AddField(
            model_name="eventsindexpage",
            name="filter_by_source",
            field=models.BooleanField(
                default=False,
                help_text="The source is the organization of the post author",
                verbose_name="Filter by source",
            ),
        ),
        migrations.AddField(
            model_name="eventsindexpage",
            name="filter_by_tag",
            field=models.BooleanField(default=True, verbose_name="Filter by tag"),
        ),
        migrations.AlterField(
            model_name="eventsindexpage",
            name="posts_per_page",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Events per page",
            ),
        ),
    ]
