# Generated by Django 5.0.7 on 2024-07-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_events", "0002_eventsindexpage_filter_by_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententrypage",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name="Location"),
        ),
        migrations.AddField(
            model_name="evententrypage",
            name="registration_url",
            field=models.URLField(blank=True, null=True, verbose_name="Registration URL"),
        ),
        migrations.AlterField(
            model_name="eventsindexpage",
            name="filter_by_source",
            field=models.BooleanField(
                default=False,
                help_text="The source is the organization of the event author",
                verbose_name="Filter by source",
            ),
        ),
    ]
