# Generated by Django 5.2.1 on 2025-05-23 16:06

from django.db import migrations
from events.models import EventEntryPage, EventsIndexPage
from itertools import chain


def migrate_obsolete_fields(apps, schema_editor):
    EventsIndexPage = apps.get_model("events", "EventsIndexPage")
    EventEntryPage = apps.get_model("events", "EventEntryPage")

    pages = chain(EventsIndexPage.objects.all(), EventEntryPage.objects.all())

    for page in pages:
        if not page.header_cta_label and not page.header_cta_link:
            continue

        if page.header_cta_buttons:
            continue

        button_block = (
            "button",
            {
                "text": page.header_cta_label,
                "button_type": "",
                "icon_class": "",
                "icon_side": "",
                "external_url": page.header_cta_link,
            },
        )

        page.header_cta_buttons = [("buttons", [button_block])]

        if page.live:
            # Save a revision and publish it
            live_page = page.get_latest_revision_as_object()
            original_last_published = live_page.last_published_at

            revision = live_page.save_revision()
            revision.publish()

            # Reset the last publication date to avoid indexing errors based on this field.
            live_page.last_published_at = original_last_published
            live_page.latest_revision_created_at = original_last_published
            live_page.save(update_fields=["last_published_at", "latest_revision_created_at"])

        else:
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0017_alter_evententrypage_body_alter_eventsindexpage_body"),
    ]

    operations = []
