# Generated by Django 5.2.1 on 2025-05-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sites_faciles_events", "0018_auto_20250523_1806"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="evententrypage",
            name="header_cta_label",
        ),
        migrations.RemoveField(
            model_name="evententrypage",
            name="header_cta_link",
        ),
        migrations.RemoveField(
            model_name="eventsindexpage",
            name="header_cta_label",
        ),
        migrations.RemoveField(
            model_name="eventsindexpage",
            name="header_cta_link",
        ),
    ]
