# Generated by Django 5.2.3 on 2025-07-02 14:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_evententrypage_preview_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententrypage",
            name="hero",
            field=wagtail.fields.StreamField(
                [("header_1", 13)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Top margin", "max_value": 15, "min_value": 0, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Bottom margin", "max_value": 15, "min_value": 0, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Primary colors", [("blue-france", "Blue France"), ("red-marianne", "Red Marianne")]),
                                ("Neutral colors", [("grey", "Grey")]),
                                (
                                    "Illustration colors",
                                    [
                                        ("green-tilleul-verveine", "Tilleul verveine"),
                                        ("green-bourgeon", "Bourgeon"),
                                        ("green-emeraude", "Émeraude"),
                                        ("green-menthe", "Menthe"),
                                        ("green-archipel", "Archipel"),
                                        ("blue-ecume", "Écume"),
                                        ("blue-cumulus", "Cumulus"),
                                        ("purple-glycine", "Glycine"),
                                        ("pink-macaron", "Macaron"),
                                        ("pink-tuile", "Tuile"),
                                        ("yellow-tournesol", "Tournesol"),
                                        ("yellow-moutarde", "Moutarde"),
                                        ("orange-terre-battue", "Terre battue"),
                                        ("brown-cafe-creme", "Café crème"),
                                        ("brown-caramel", "Caramel"),
                                        ("brown-opera", "Opéra"),
                                        ("beige-gris-galet", "Gris galet"),
                                    ],
                                ),
                            ],
                            "help_text": "Uses the French Design System colors",
                            "label": "Background color",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Button label", "required": False}),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-btn", "Primary"),
                                ("fr-btn fr-btn--secondary", "Secundary"),
                                ("fr-btn fr-btn--tertiary", "Tertiary"),
                                ("fr-btn fr-btn--tertiary-no-outline", "Tertiary without border"),
                            ],
                            "label": "Button type",
                            "required": False,
                        },
                    ),
                    8: ("content_manager.blocks.IconPickerBlock", (), {"label": "Icon", "required": False}),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("fr-btn--icon-left", "Left"), ("fr-btn--icon-right", "Right")],
                            "label": "Icon side",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "The title of your header",
                            "help_text": "The title that will appear in the header of your page",
                            "label": "Title header",
                        },
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "Add a short description of your organisation here to help visitors easily understand what you do.",
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "help_text": "To give a brief description of what you do",
                            "label": "Text",
                            "required": False,
                        },
                    ),
                    12: ("wagtail.blocks.ChoiceBlock", [], {"choices": [("left", "Left"), ("right", "Right")]}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("top_margin", 0),
                                ("bottom_margin", 1),
                                ("background_color", 2),
                                ("page", 3),
                                ("document", 4),
                                ("external_url", 5),
                                ("text", 6),
                                ("button_type", 7),
                                ("icon_class", 8),
                                ("icon_side", 9),
                                ("hero_title", 10),
                                ("hero_subtitle", 11),
                                ("position", 12),
                            ]
                        ],
                        {"label": "En-tête 1"},
                    ),
                },
            ),
        ),
        migrations.AddField(
            model_name="eventsindexpage",
            name="hero",
            field=wagtail.fields.StreamField(
                [("header_1", 13)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Top margin", "max_value": 15, "min_value": 0, "required": False},
                    ),
                    1: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Bottom margin", "max_value": 15, "min_value": 0, "required": False},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Primary colors", [("blue-france", "Blue France"), ("red-marianne", "Red Marianne")]),
                                ("Neutral colors", [("grey", "Grey")]),
                                (
                                    "Illustration colors",
                                    [
                                        ("green-tilleul-verveine", "Tilleul verveine"),
                                        ("green-bourgeon", "Bourgeon"),
                                        ("green-emeraude", "Émeraude"),
                                        ("green-menthe", "Menthe"),
                                        ("green-archipel", "Archipel"),
                                        ("blue-ecume", "Écume"),
                                        ("blue-cumulus", "Cumulus"),
                                        ("purple-glycine", "Glycine"),
                                        ("pink-macaron", "Macaron"),
                                        ("pink-tuile", "Tuile"),
                                        ("yellow-tournesol", "Tournesol"),
                                        ("yellow-moutarde", "Moutarde"),
                                        ("orange-terre-battue", "Terre battue"),
                                        ("brown-cafe-creme", "Café crème"),
                                        ("brown-caramel", "Caramel"),
                                        ("brown-opera", "Opéra"),
                                        ("beige-gris-galet", "Gris galet"),
                                    ],
                                ),
                            ],
                            "help_text": "Uses the French Design System colors",
                            "label": "Background color",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    6: ("wagtail.blocks.CharBlock", (), {"label": "Button label", "required": False}),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-btn", "Primary"),
                                ("fr-btn fr-btn--secondary", "Secundary"),
                                ("fr-btn fr-btn--tertiary", "Tertiary"),
                                ("fr-btn fr-btn--tertiary-no-outline", "Tertiary without border"),
                            ],
                            "label": "Button type",
                            "required": False,
                        },
                    ),
                    8: ("content_manager.blocks.IconPickerBlock", (), {"label": "Icon", "required": False}),
                    9: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("fr-btn--icon-left", "Left"), ("fr-btn--icon-right", "Right")],
                            "label": "Icon side",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "The title of your header",
                            "help_text": "The title that will appear in the header of your page",
                            "label": "Title header",
                        },
                    ),
                    11: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "Add a short description of your organisation here to help visitors easily understand what you do.",
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "strikethrough",
                            ],
                            "help_text": "To give a brief description of what you do",
                            "label": "Text",
                            "required": False,
                        },
                    ),
                    12: ("wagtail.blocks.ChoiceBlock", [], {"choices": [("left", "Left"), ("right", "Right")]}),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("top_margin", 0),
                                ("bottom_margin", 1),
                                ("background_color", 2),
                                ("page", 3),
                                ("document", 4),
                                ("external_url", 5),
                                ("text", 6),
                                ("button_type", 7),
                                ("icon_class", 8),
                                ("icon_side", 9),
                                ("hero_title", 10),
                                ("hero_subtitle", 11),
                                ("position", 12),
                            ]
                        ],
                        {"label": "En-tête 1"},
                    ),
                },
            ),
        ),
    ]
