# Generated by Django 5.2.7 on 2025-11-06 14:47

import django.core.validators
import re
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_alter_evententrypage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evententrypage",
            name="hero",
            field=wagtail.fields.StreamField(
                [
                    ("hero_text_image", 20),
                    ("hero_text_wide_image", 28),
                    ("hero_text_background_image", 35),
                    ("old_hero", 43),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "The title of your header",
                            "help_text": "The title that will appear in the header of your page. If there is no header, the page title will appear.",
                            "label": "Title header",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "Add a short description of your organisation here to help visitors easily understand what you do.",
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "text-left",
                                "text-center",
                                "text-right",
                            ],
                            "help_text": "To give a brief description of what you do",
                            "label": "Text",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "help_text": "This field allows you to define the placement of text relative to adjacent content.",
                            "label": "Text content position",
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_title", 0), ("hero_subtitle", 1), ("position", 2)]],
                        {"label": "Text content"},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("document", "Document"),
                                ("anchor", "Anchor link"),
                            ],
                            "help_text": "Select the type of link.",
                            "label": "Link type",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Link to an anchor block on the page. Allowed characters: A-Z, a-z, 0-9, - and _.",
                            "label": "Anchor ID",
                            "required": False,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                    "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                    "invalid",
                                )
                            ],
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Button label", "required": False}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-btn", "Primary"),
                                ("fr-btn fr-btn--secondary", "Secundary"),
                                ("fr-btn fr-btn--tertiary", "Tertiary"),
                                ("fr-btn fr-btn--tertiary-no-outline", "Tertiary without border"),
                            ],
                            "label": "Button type",
                            "required": False,
                        },
                    ),
                    11: (
                        "content_manager.blocks.buttons_links.IconPickerBlock",
                        (),
                        {"label": "Icon", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("fr-btn--icon-left", "Left"), ("fr-btn--icon-right", "Right")],
                            "label": "Icon side",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 4),
                                ("page", 5),
                                ("document", 6),
                                ("external_url", 7),
                                ("anchor", 8),
                                ("text", 9),
                                ("button_type", 10),
                                ("icon_class", 11),
                                ("icon_side", 12),
                            ]
                        ],
                        {"label": "Button"},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {
                            "default": [
                                {
                                    "anchor": "",
                                    "button_type": "fr-btn",
                                    "external_url": "https://sites.beta.gouv.fr/contactez-nous/",
                                    "icon_side": "--",
                                    "link_type": "external_url",
                                    "text": "Nous contacter",
                                },
                                {
                                    "anchor": "",
                                    "button_type": "fr-btn fr-btn--secondary",
                                    "external_url": "https://tube.numerique.gouv.fr/",
                                    "icon_side": "--",
                                    "link_type": "external_url",
                                    "text": "Voir la vidéo",
                                },
                            ],
                            "help_text": "Please use only one primary button.\n            If you use icons, use them on all buttons and align them on the same side.",
                            "label": "Buttons",
                        },
                    ),
                    15: ("wagtail.images.blocks.ImageBlock", [], {"label": "Hero image"}),
                    16: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Top margin", "max_value": 15, "min_value": 0, "required": False},
                    ),
                    17: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Bottom margin", "max_value": 15, "min_value": 0, "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Primary colors", [("blue-france", "Blue France"), ("red-marianne", "Red Marianne")]),
                                ("Neutral colors", [("grey", "Grey")]),
                                (
                                    "Illustration colors",
                                    [
                                        ("green-tilleul-verveine", "Tilleul verveine"),
                                        ("green-bourgeon", "Bourgeon"),
                                        ("green-emeraude", "Émeraude"),
                                        ("green-menthe", "Menthe"),
                                        ("green-archipel", "Archipel"),
                                        ("blue-ecume", "Écume"),
                                        ("blue-cumulus", "Cumulus"),
                                        ("purple-glycine", "Glycine"),
                                        ("pink-macaron", "Macaron"),
                                        ("pink-tuile", "Tuile"),
                                        ("yellow-tournesol", "Tournesol"),
                                        ("yellow-moutarde", "Moutarde"),
                                        ("orange-terre-battue", "Terre battue"),
                                        ("brown-cafe-creme", "Café crème"),
                                        ("brown-caramel", "Caramel"),
                                        ("brown-opera", "Opéra"),
                                        ("beige-gris-galet", "Gris galet"),
                                    ],
                                ),
                            ],
                            "help_text": "Uses the French Design System colors.<br>If you want to design a classic website, choose the colour ‘white’ or ‘French blue’.",
                            "label": "Background color",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("top_margin", 16), ("bottom_margin", 17), ("background_color", 18)]],
                        {"label": "Layout"},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("text_content", 3), ("buttons", 14), ("image", 15), ("layout", 19)]],
                        {"label": "Header with an image and text"},
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("bottom", "Bottom")],
                            "help_text": "This field allows you to define the placement of text relative to adjacent content in vertical position.",
                            "label": "Text content position",
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_title", 0), ("hero_subtitle", 1), ("position", 21)]],
                        {"label": "Text content"},
                    ),
                    23: ("wagtail.images.blocks.ImageBlock", [], {"label": "Image"}),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                                ("", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Choose the part of the image to highlight",
                            "label": "Image positioning",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-content-media--sm", "Small"),
                                ("", "Medium"),
                                ("fr-content-media--lg", "Large"),
                            ],
                            "help_text": "Select image width",
                            "label": "Image width",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-ratio-32x9", "32x9"),
                                ("fr-ratio-16x9", "16x9"),
                                ("fr-ratio-3x2", "3x2"),
                                ("fr-ratio-4x3", "4x3"),
                                ("fr-ratio-1x1", "1x1"),
                                ("fr-ratio-3x4", "3x4"),
                                ("fr-ratio-2x3", "2x3"),
                            ],
                            "help_text": "Select the right ratio for your image. The size will be adjusted on mobile phones, so make sure you don't include any text in the image.",
                            "label": "Image ratio",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 23), ("image_positioning", 24), ("image_width", 25), ("image_ratio", 26)]],
                        {"label": "Hero image"},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text_content", 22), ("layout", 19), ("buttons", 14), ("image", 27)]],
                        {"label": "Vertical header with a banner and text"},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("", "Center"), ("right", "Right")],
                            "help_text": "This field allows you to define the placement of text.",
                            "label": "Text content position",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_title", 0), ("hero_subtitle", 1), ("position", 29)]],
                        {"label": "Text content"},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("color", "Color"), ("image", "Image")],
                            "help_text": "Choose if you prefer a background image or a background color.",
                            "label": "Background Color or Image",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("bottom", "Bottom"), ("", "Center")],
                            "help_text": "Choose the part of the image to highlight",
                            "label": "Image positioning",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("darken", "Darken"), ("lighten", "Lighten")],
                            "help_text": "Add a mask to lighten or darken the image",
                            "label": "Image mask",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 23), ("image_positioning", 32), ("image_mask", 33)]],
                        {"label": "Hero image"},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text_content", 30),
                                ("buttons", 14),
                                ("background_color_or_image", 31),
                                ("image", 34),
                                ("background_color", 18),
                            ]
                        ],
                        {"label": "Header with background"},
                    ),
                    36: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Show title in header image?", "required": False},
                    ),
                    37: ("wagtail.images.blocks.ImageBlock", [], {"label": "Header image"}),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Primary colors", [("blue-france", "Blue France"), ("red-marianne", "Red Marianne")]),
                                ("Neutral colors", [("grey", "Grey")]),
                                (
                                    "Illustration colors",
                                    [
                                        ("green-tilleul-verveine", "Tilleul verveine"),
                                        ("green-bourgeon", "Bourgeon"),
                                        ("green-emeraude", "Émeraude"),
                                        ("green-menthe", "Menthe"),
                                        ("green-archipel", "Archipel"),
                                        ("blue-ecume", "Écume"),
                                        ("blue-cumulus", "Cumulus"),
                                        ("purple-glycine", "Glycine"),
                                        ("pink-macaron", "Macaron"),
                                        ("pink-tuile", "Tuile"),
                                        ("yellow-tournesol", "Tournesol"),
                                        ("yellow-moutarde", "Moutarde"),
                                        ("orange-terre-battue", "Terre battue"),
                                        ("brown-cafe-creme", "Café crème"),
                                        ("brown-caramel", "Caramel"),
                                        ("brown-opera", "Opéra"),
                                        ("beige-gris-galet", "Gris galet"),
                                    ],
                                ),
                            ],
                            "help_text": "Uses the French Design System colors. Apply only if there is no header image.",
                            "label": "Background color",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the title will be centered on the header.",
                            "label": "Centered title",
                            "required": False,
                        },
                    ),
                    40: ("wagtail.blocks.BooleanBlock", (), {"label": "Darken background image", "required": False}),
                    41: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"blank": True, "label": "Call to action text", "null": True, "required": False},
                    ),
                    42: ("wagtail.blocks.StreamBlock", [[("button", 13)]], {"label": "Buttons", "required": False}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header_with_title", 36),
                                ("header_image", 37),
                                ("header_color_class", 38),
                                ("header_large", 39),
                                ("header_darken", 40),
                                ("header_cta_text", 41),
                                ("header_cta_buttons", 42),
                            ]
                        ],
                        {"label": "Configurable header"},
                    ),
                },
            ),
        ),
        migrations.AlterField(
            model_name="eventsindexpage",
            name="hero",
            field=wagtail.fields.StreamField(
                [
                    ("hero_text_image", 20),
                    ("hero_text_wide_image", 28),
                    ("hero_text_background_image", 35),
                    ("old_hero", 43),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "The title of your header",
                            "help_text": "The title that will appear in the header of your page. If there is no header, the page title will appear.",
                            "label": "Title header",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "default": "Add a short description of your organisation here to help visitors easily understand what you do.",
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "document-link",
                                "superscript",
                                "subscript",
                                "strikethrough",
                                "text-left",
                                "text-center",
                                "text-right",
                            ],
                            "help_text": "To give a brief description of what you do",
                            "label": "Text",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("right", "Right")],
                            "help_text": "This field allows you to define the placement of text relative to adjacent content.",
                            "label": "Text content position",
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_title", 0), ("hero_subtitle", 1), ("position", 2)]],
                        {"label": "Text content"},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("external_url", "External URL"),
                                ("document", "Document"),
                                ("anchor", "Anchor link"),
                            ],
                            "help_text": "Select the type of link.",
                            "label": "Link type",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "",
                            "help_text": "Link to an anchor block on the page. Allowed characters: A-Z, a-z, 0-9, - and _.",
                            "label": "Anchor ID",
                            "required": False,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                    "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                    "invalid",
                                )
                            ],
                        },
                    ),
                    9: ("wagtail.blocks.CharBlock", (), {"label": "Button label", "required": False}),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-btn", "Primary"),
                                ("fr-btn fr-btn--secondary", "Secundary"),
                                ("fr-btn fr-btn--tertiary", "Tertiary"),
                                ("fr-btn fr-btn--tertiary-no-outline", "Tertiary without border"),
                            ],
                            "label": "Button type",
                            "required": False,
                        },
                    ),
                    11: (
                        "content_manager.blocks.buttons_links.IconPickerBlock",
                        (),
                        {"label": "Icon", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("fr-btn--icon-left", "Left"), ("fr-btn--icon-right", "Right")],
                            "label": "Icon side",
                            "required": False,
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 4),
                                ("page", 5),
                                ("document", 6),
                                ("external_url", 7),
                                ("anchor", 8),
                                ("text", 9),
                                ("button_type", 10),
                                ("icon_class", 11),
                                ("icon_side", 12),
                            ]
                        ],
                        {"label": "Button"},
                    ),
                    14: (
                        "wagtail.blocks.ListBlock",
                        (13,),
                        {
                            "default": [
                                {
                                    "anchor": "",
                                    "button_type": "fr-btn",
                                    "external_url": "https://sites.beta.gouv.fr/contactez-nous/",
                                    "icon_side": "--",
                                    "link_type": "external_url",
                                    "text": "Nous contacter",
                                },
                                {
                                    "anchor": "",
                                    "button_type": "fr-btn fr-btn--secondary",
                                    "external_url": "https://tube.numerique.gouv.fr/",
                                    "icon_side": "--",
                                    "link_type": "external_url",
                                    "text": "Voir la vidéo",
                                },
                            ],
                            "help_text": "Please use only one primary button.\n            If you use icons, use them on all buttons and align them on the same side.",
                            "label": "Buttons",
                        },
                    ),
                    15: ("wagtail.images.blocks.ImageBlock", [], {"label": "Hero image"}),
                    16: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Top margin", "max_value": 15, "min_value": 0, "required": False},
                    ),
                    17: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {"default": 5, "label": "Bottom margin", "max_value": 15, "min_value": 0, "required": False},
                    ),
                    18: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Primary colors", [("blue-france", "Blue France"), ("red-marianne", "Red Marianne")]),
                                ("Neutral colors", [("grey", "Grey")]),
                                (
                                    "Illustration colors",
                                    [
                                        ("green-tilleul-verveine", "Tilleul verveine"),
                                        ("green-bourgeon", "Bourgeon"),
                                        ("green-emeraude", "Émeraude"),
                                        ("green-menthe", "Menthe"),
                                        ("green-archipel", "Archipel"),
                                        ("blue-ecume", "Écume"),
                                        ("blue-cumulus", "Cumulus"),
                                        ("purple-glycine", "Glycine"),
                                        ("pink-macaron", "Macaron"),
                                        ("pink-tuile", "Tuile"),
                                        ("yellow-tournesol", "Tournesol"),
                                        ("yellow-moutarde", "Moutarde"),
                                        ("orange-terre-battue", "Terre battue"),
                                        ("brown-cafe-creme", "Café crème"),
                                        ("brown-caramel", "Caramel"),
                                        ("brown-opera", "Opéra"),
                                        ("beige-gris-galet", "Gris galet"),
                                    ],
                                ),
                            ],
                            "help_text": "Uses the French Design System colors.<br>If you want to design a classic website, choose the colour ‘white’ or ‘French blue’.",
                            "label": "Background color",
                            "required": False,
                        },
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("top_margin", 16), ("bottom_margin", 17), ("background_color", 18)]],
                        {"label": "Layout"},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("text_content", 3), ("buttons", 14), ("image", 15), ("layout", 19)]],
                        {"label": "Header with an image and text"},
                    ),
                    21: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("bottom", "Bottom")],
                            "help_text": "This field allows you to define the placement of text relative to adjacent content in vertical position.",
                            "label": "Text content position",
                        },
                    ),
                    22: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_title", 0), ("hero_subtitle", 1), ("position", 21)]],
                        {"label": "Text content"},
                    ),
                    23: ("wagtail.images.blocks.ImageBlock", [], {"label": "Image"}),
                    24: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("top", "Top"),
                                ("bottom", "Bottom"),
                                ("left", "Left"),
                                ("", "Center"),
                                ("right", "Right"),
                            ],
                            "help_text": "Choose the part of the image to highlight",
                            "label": "Image positioning",
                            "required": False,
                        },
                    ),
                    25: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-content-media--sm", "Small"),
                                ("", "Medium"),
                                ("fr-content-media--lg", "Large"),
                            ],
                            "help_text": "Select image width",
                            "label": "Image width",
                            "required": False,
                        },
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("fr-ratio-32x9", "32x9"),
                                ("fr-ratio-16x9", "16x9"),
                                ("fr-ratio-3x2", "3x2"),
                                ("fr-ratio-4x3", "4x3"),
                                ("fr-ratio-1x1", "1x1"),
                                ("fr-ratio-3x4", "3x4"),
                                ("fr-ratio-2x3", "2x3"),
                            ],
                            "help_text": "Select the right ratio for your image. The size will be adjusted on mobile phones, so make sure you don't include any text in the image.",
                            "label": "Image ratio",
                            "required": False,
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 23), ("image_positioning", 24), ("image_width", 25), ("image_ratio", 26)]],
                        {"label": "Hero image"},
                    ),
                    28: (
                        "wagtail.blocks.StructBlock",
                        [[("text_content", 22), ("layout", 19), ("buttons", 14), ("image", 27)]],
                        {"label": "Vertical header with a banner and text"},
                    ),
                    29: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("left", "Left"), ("", "Center"), ("right", "Right")],
                            "help_text": "This field allows you to define the placement of text.",
                            "label": "Text content position",
                            "required": False,
                        },
                    ),
                    30: (
                        "wagtail.blocks.StructBlock",
                        [[("hero_title", 0), ("hero_subtitle", 1), ("position", 29)]],
                        {"label": "Text content"},
                    ),
                    31: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("color", "Color"), ("image", "Image")],
                            "help_text": "Choose if you prefer a background image or a background color.",
                            "label": "Background Color or Image",
                            "required": False,
                        },
                    ),
                    32: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("top", "Top"), ("bottom", "Bottom"), ("", "Center")],
                            "help_text": "Choose the part of the image to highlight",
                            "label": "Image positioning",
                            "required": False,
                        },
                    ),
                    33: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("darken", "Darken"), ("lighten", "Lighten")],
                            "help_text": "Add a mask to lighten or darken the image",
                            "label": "Image mask",
                            "required": False,
                        },
                    ),
                    34: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 23), ("image_positioning", 32), ("image_mask", 33)]],
                        {"label": "Hero image"},
                    ),
                    35: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text_content", 30),
                                ("buttons", 14),
                                ("background_color_or_image", 31),
                                ("image", 34),
                                ("background_color", 18),
                            ]
                        ],
                        {"label": "Header with background"},
                    ),
                    36: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {"label": "Show title in header image?", "required": False},
                    ),
                    37: ("wagtail.images.blocks.ImageBlock", [], {"label": "Header image"}),
                    38: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("Primary colors", [("blue-france", "Blue France"), ("red-marianne", "Red Marianne")]),
                                ("Neutral colors", [("grey", "Grey")]),
                                (
                                    "Illustration colors",
                                    [
                                        ("green-tilleul-verveine", "Tilleul verveine"),
                                        ("green-bourgeon", "Bourgeon"),
                                        ("green-emeraude", "Émeraude"),
                                        ("green-menthe", "Menthe"),
                                        ("green-archipel", "Archipel"),
                                        ("blue-ecume", "Écume"),
                                        ("blue-cumulus", "Cumulus"),
                                        ("purple-glycine", "Glycine"),
                                        ("pink-macaron", "Macaron"),
                                        ("pink-tuile", "Tuile"),
                                        ("yellow-tournesol", "Tournesol"),
                                        ("yellow-moutarde", "Moutarde"),
                                        ("orange-terre-battue", "Terre battue"),
                                        ("brown-cafe-creme", "Café crème"),
                                        ("brown-caramel", "Caramel"),
                                        ("brown-opera", "Opéra"),
                                        ("beige-gris-galet", "Gris galet"),
                                    ],
                                ),
                            ],
                            "help_text": "Uses the French Design System colors. Apply only if there is no header image.",
                            "label": "Background color",
                            "required": False,
                        },
                    ),
                    39: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "help_text": "If checked, the title will be centered on the header.",
                            "label": "Centered title",
                            "required": False,
                        },
                    ),
                    40: ("wagtail.blocks.BooleanBlock", (), {"label": "Darken background image", "required": False}),
                    41: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"blank": True, "label": "Call to action text", "null": True, "required": False},
                    ),
                    42: ("wagtail.blocks.StreamBlock", [[("button", 13)]], {"label": "Buttons", "required": False}),
                    43: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("header_with_title", 36),
                                ("header_image", 37),
                                ("header_color_class", 38),
                                ("header_large", 39),
                                ("header_darken", 40),
                                ("header_cta_text", 41),
                                ("header_cta_buttons", 42),
                            ]
                        ],
                        {"label": "Configurable header"},
                    ),
                },
            ),
        ),
    ]
