# Generated by Django 6.0.3 on 2026-03-19 10:49

from django.db import migrations
from itertools import chain


def invert_text_position(apps, schema_editor):
    EventEntryPage = apps.get_model("events", "EventEntryPage")
    EventsIndexPage = apps.get_model("events", "EventsIndexPage")

    pages = chain(EventEntryPage.objects.all(), EventsIndexPage.objects.all())

    for page in pages:
        if not hasattr(page, "hero"):
            continue

        stream_data = page.hero.raw_data
        updated = False

        for block in stream_data:
            if block["type"] == "hero_text_wide_image":
                value = block.get("value", {})
                text_content = value.get("text_content", {})

                position = text_content.get("position")

                if position == "top":
                    text_content["position"] = "bottom"
                    updated = True
                elif position == "bottom":
                    text_content["position"] = "top"
                    updated = True

        if updated:
            page.hero = stream_data
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0028_alter_evententrypage_body_alter_eventsindexpage_body"),
    ]

    operations = [
        migrations.RunPython(invert_text_position),
    ]
