# Generated by Django 6.0.3 on 2026-03-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0030_invert_hero_text_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="evententrypage",
            name="exclude_from_sitemap",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will be excluded from sitemap.xml, the plan du site page, and will have a noindex meta tag.",
                verbose_name="Exclude from sitemap",
            ),
        ),
        migrations.AddField(
            model_name="eventsindexpage",
            name="exclude_from_sitemap",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will be excluded from sitemap.xml, the plan du site page, and will have a noindex meta tag.",
                verbose_name="Exclude from sitemap",
            ),
        ),
    ]
