# Generated by Django 5.2.3 on 2025-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_alter_formfield_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpage",
            name="honeypot",
            field=models.BooleanField(default=False, verbose_name="Honeypot Enabled"),
        ),
    ]
