# Generated by Django 5.2.3 on 2025-06-20 16:09

import wagtail_honeypot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_faciles_forms", "0002_alter_formfield_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="formpage",
            name="honeypot",
            field=models.BooleanField(
                default=wagtail_honeypot.models.get_honeypot_default, verbose_name="Honeypot enabled"
            ),
        ),
    ]
