# Generated by Django 5.0.10 on 2025-11-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_formpage_honeypot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formpage",
            name="honeypot",
            field=models.BooleanField(default=False, verbose_name="Honeypot Enabled"),
        ),
    ]
