# Generated by Django 5.0.2 on 2024-03-05 18:04

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_blog", "0004_alter_blogentrypage_body_alter_blogindexpage_body"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Tag",
        ),
        migrations.AddField(
            model_name="blogentrypage",
            name="header_cta_text",
            field=models.CharField(blank=True, null=True, verbose_name="Call to action text"),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="header_cta_text",
            field=models.CharField(blank=True, null=True, verbose_name="Call to action text"),
        ),
        migrations.AlterField(
            model_name="blogentrypage",
            name="blog_categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, through="sites_faciles_blog.CategoryEntryPage", to="sites_faciles_blog.category", verbose_name="Categories"
            ),
        ),
        migrations.AlterField(
            model_name="blogentrypage",
            name="header_cta_label",
            field=models.CharField(blank=True, null=True, verbose_name="Call to action label"),
        ),
        migrations.AlterField(
            model_name="blogentrypage",
            name="header_cta_link",
            field=models.URLField(blank=True, null=True, verbose_name="Call to action link"),
        ),
        migrations.AlterField(
            model_name="blogentrypage",
            name="header_darken",
            field=models.BooleanField(default=False, verbose_name="Darken background image"),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="header_cta_label",
            field=models.CharField(blank=True, null=True, verbose_name="Call to action label"),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="header_cta_link",
            field=models.URLField(blank=True, null=True, verbose_name="Call to action link"),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="header_darken",
            field=models.BooleanField(default=False, verbose_name="Darken background image"),
        ),
    ]
