# Generated by Django 5.0.6 on 2024-07-08 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_blog", "0022_blogindexpage_filter_by_author_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("slug", models.SlugField(max_length=80)),
            ],
        ),
        migrations.AddField(
            model_name="person",
            name="organization_item",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="sites_faciles_blog.organization"
            ),
        ),
    ]
