# Generated by Django 5.0.6 on 2024-07-08 15:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_blog", "0025_remove_person_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={"verbose_name": "Organization"},
        ),
    ]
