# Generated by Django 6.0.3 on 2026-03-10 14:07
from django.db import migrations


def copy_images(apps, schema_editor):
    OldImage = apps.get_model("wagtailimages", "Image")
    NewImage = apps.get_model("customimages", "CustomImage")

    for image in OldImage.objects.all():
        NewImage.objects.create(
            id=image.id,
            title=image.title,
            file=image.file,
            width=image.width,
            height=image.height,
            created_at=image.created_at,
            uploaded_by_user=image.uploaded_by_user,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("customimages", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RunPython(copy_images, migrations.RunPython.noop),
    ]
