# Generated by Django 5.0.2 on 2024-02-13 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_blogentrypage_blog_categories_blogentrypage_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogentrypage",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="Post date"),
        ),
    ]
