# Generated by Django 5.0.3 on 2024-03-21 13:54

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_delete_tag_blogentrypage_header_cta_text_and_more"),
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("role", models.CharField(max_length=255, verbose_name="Function")),
                (
                    "author_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Author",
            },
        ),
        migrations.AddField(
            model_name="blogentrypage",
            name="authors",
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to="blog.author"),
        ),
    ]
