# Generated by Django 5.0.3 on 2024-03-25 16:48

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_author_blogentrypage_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="colophon",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Text displayed at the end of every page in the category",
                max_length=500,
                verbose_name="Colophon",
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="role",
            field=models.CharField(max_length=255, verbose_name="Role"),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Displayed on the top of the category page",
                max_length=500,
                verbose_name="Description",
            ),
        ),
    ]
