# Generated by Django 5.0.2 on 2024-02-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_blogentrypage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentrypage",
            name="blog_categories",
            field=models.ManyToManyField(
                blank=True, null=True, through="blog.CategoryEntryPage", to="blog.category", verbose_name="Categories"
            ),
        ),
    ]
