# Generated by Django 5.0.2 on 2024-02-20 13:56

import django.core.validators
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_alter_blogentrypage_blog_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="posts_per_page",
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Posts per page",
            ),
        ),
        migrations.AlterField(
            model_name="blogentrypage",
            name="blog_categories",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, null=True, through="blog.CategoryEntryPage", to="blog.category", verbose_name="Categories"
            ),
        ),
    ]
