# Generated by Django 5.0.6 on 2024-06-18 12:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_blog", "0018_alter_blogentrypage_body_alter_blogindexpage_body_and_more"),
    ]

    operations = []
