# Generated by Django 5.0.6 on 2024-06-18 13:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_alter_blogentrypage_body_alter_blogindexpage_body"),
        ("blog", "0019_merge_20240618_1446"),
    ]

    operations = []
