# Generated by Django 5.1.1 on 2024-09-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_blog", "0035_alter_blogentrypage_body_alter_blogindexpage_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogentrypage",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="For imported pages, to allow updates.", null=True, verbose_name="Source URL"
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="source_url",
            field=models.URLField(
                blank=True, help_text="For imported pages, to allow updates.", null=True, verbose_name="Source URL"
            ),
        ),
    ]
