# Generated by Django 5.2.1 on 2025-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_faciles_blog", "0043_alter_blogentrypage_body_alter_blogindexpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentrypage",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="For imported pages, to allow updates. Max length: 2000 characters.",
                max_length=2000,
                null=True,
                verbose_name="Source URL",
            ),
        ),
        migrations.AlterField(
            model_name="blogindexpage",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="For imported pages, to allow updates. Max length: 2000 characters.",
                max_length=2000,
                null=True,
                verbose_name="Source URL",
            ),
        ),
    ]
