# Generated by Django 5.2.1 on 2025-05-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0046_auto_20250523_1759"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogentrypage",
            name="header_cta_label",
        ),
        migrations.RemoveField(
            model_name="blogentrypage",
            name="header_cta_link",
        ),
        migrations.RemoveField(
            model_name="blogindexpage",
            name="header_cta_label",
        ),
        migrations.RemoveField(
            model_name="blogindexpage",
            name="header_cta_link",
        ),
    ]
