# Generated by Django 5.2.1 on 2025-06-13 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sites_faciles_blog", "0047_remove_blogentrypage_header_cta_label_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogentrypage",
            name="preview_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed as a preview when the page is shared on social media",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Preview image",
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="preview_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image displayed as a preview when the page is shared on social media",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Preview image",
            ),
        ),
    ]
