# Generated by Django 6.0.3 on 2026-03-19 15:23

from django.db import migrations
from itertools import chain


def invert_text_position(apps, schema_editor):
    BlogEntryPage = apps.get_model("blog", "BlogEntryPage")
    BlogIndexPage = apps.get_model("blog", "BlogIndexPage")

    pages = chain(BlogEntryPage.objects.all(), BlogIndexPage.objects.all())

    for page in pages:
        if not hasattr(page, "hero"):
            continue

        stream_data = page.hero.raw_data
        updated = False

        for block in stream_data:
            if block["type"] == "hero_text_wide_image":
                value = block.get("value", {})
                text_content = value.get("text_content", {})

                position = text_content.get("position")

                if position == "top":
                    text_content["position"] = "bottom"
                    updated = True
                elif position == "bottom":
                    text_content["position"] = "top"
                    updated = True

            if updated:
                page.hero = stream_data
                page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0057_alter_blogentrypage_body_and_more"),
    ]

    operations = [
        migrations.RunPython(invert_text_position, reverse_code=migrations.RunPython.noop),
    ]
