# Generated by Django 6.0.3 on 2026-03-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoredFile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Full storage path (e.g. 'images/my_photo.jpg')",
                        max_length=512,
                        unique=True,
                    ),
                ),
                ("content", models.BinaryField(help_text="Raw file bytes")),
                (
                    "content_type",
                    models.CharField(
                        blank=True, default="", help_text="MIME type (e.g. 'image/jpeg')", max_length=256
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0, help_text="File size in bytes")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "stored file",
                "verbose_name_plural": "stored files",
                "ordering": ["name"],
            },
        ),
    ]
