{{- if .Values.ingress.enabled -}}
{{- $fullName := include "sites-faciles.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "sites-faciles.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls.enabled }}
  tls:
    {{- if .Values.ingress.host }}
    - secretName: {{ .Values.ingress.tls.secretName | default (printf "%s-tls" $fullName) | quote }}
      hosts:
        - {{ .Values.ingress.host | quote }}
    {{- end }}
    {{- range .Values.ingress.tls.additional }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ .Values.ingress.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "sites-faciles.fullname" . }}
                port:
                  number: {{ .Values.backend.service.port }}
          {{- with .Values.ingress.customBackends }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
    {{- end }}
    {{- range .Values.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.path | quote }}
            pathType: Prefix
            backend:
              service:
                name: {{ include "sites-faciles.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- with $.Values.ingress.customBackends }}
            {{- toYaml . | nindent 10 }}
          {{- end }}
    {{- end }}
{{- end }}
