# Generated by Django 4.1.10 on 2023-11-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("content_manager", "0006_analyticssettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="CmsDsfrConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "header_brand",
                    models.CharField(
                        blank=True,
                        default="République française",
                        max_length=200,
                        verbose_name="Institution (en-tête)",
                    ),
                ),
                (
                    "header_brand_html",
                    models.CharField(
                        blank=True,
                        default="République<br />française",
                        max_length=200,
                        verbose_name="Institution avec césure (en-tête)",
                    ),
                ),
                (
                    "footer_brand",
                    models.CharField(
                        blank=True, default="République française", max_length=200, verbose_name="Institution (pied)"
                    ),
                ),
                (
                    "footer_brand_html",
                    models.CharField(
                        blank=True,
                        default="République<br />française",
                        max_length=200,
                        verbose_name="Institution avec césure (pied)",
                    ),
                ),
                (
                    "brand_html",
                    models.CharField(
                        blank=True,
                        default="République<br />française",
                        max_length=200,
                        verbose_name="Institution avec césure (en-tête)",
                    ),
                ),
                (
                    "site_title",
                    models.CharField(
                        blank=True, default="Titre du site", max_length=200, verbose_name="Titre du site"
                    ),
                ),
                (
                    "site_tagline",
                    models.CharField(
                        blank=True, default="Sous-titre du site", max_length=200, verbose_name="Sous-titre du site"
                    ),
                ),
                ("footer_description", models.TextField(blank=True, default="", verbose_name="Description")),
                ("mourning", models.BooleanField(default=False, verbose_name="Mise en berne")),
                (
                    "site",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuration du site",
            },
        ),
    ]
