# Generated by Django 4.2.7 on 2023-11-27 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("content_manager", "0009_cmsdsfrconfig_footer_theme_modale_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cmsdsfrconfig",
            old_name="footer_theme_modale",
            new_name="theme_modale_button",
        ),
    ]
