# Generated by Django 5.0.4 on 2024-04-24 14:08

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_content_manager", "0022_alter_cmsdsfrconfig_options_cmsdsfrconfig_beta_tag_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsdsfrconfig",
            name="footer_description",
            field=wagtail.fields.RichTextField(blank=True, default="", verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="cmsdsfrconfig",
            name="notice",
            field=wagtail.fields.RichTextField(
                blank=True,
                default="",
                help_text="The important notice banner should only be used for essential and temporary information.             (Excessive or continuous use risks “drowning” the message.)",
                verbose_name="Important notice",
            ),
        ),
        migrations.CreateModel(
            name="SocialMediaItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                ("title", models.CharField(blank=True, default="", max_length=200, verbose_name="Title")),
                ("url", models.URLField(blank=True, default="", verbose_name="URL")),
                ("icon_class", models.CharField(blank=True, default="", max_length=200, verbose_name="Icon class")),
                (
                    "site_config",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_items",
                        to="sites_faciles_content_manager.cmsdsfrconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
