# Generated by Django 5.0.4 on 2024-04-24 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites_faciles_content_manager", "0023_alter_cmsdsfrconfig_footer_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="socialmediaitem",
            options={"verbose_name": "Social media item", "verbose_name_plural": "Social media items"},
        ),
    ]
