# Generated by Django 5.1.6 on 2025-02-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0052_alter_catalogindexpage_body_alter_contentpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmsdsfrconfig",
            name="header_login_button",
            field=models.BooleanField(default=False, verbose_name="Show a login button in the header"),
        ),
    ]
