# Generated by Django 5.2.1 on 2025-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0055_alter_catalogindexpage_body_alter_contentpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalogindexpage",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="For imported pages, to allow updates. Max length: 2000 characters.",
                max_length=2000,
                null=True,
                verbose_name="Source URL",
            ),
        ),
        migrations.AlterField(
            model_name="cmsdsfrconfig",
            name="newsletter_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Max length: 2000 characters.",
                max_length=2000,
                verbose_name="Newsletter registration URL",
            ),
        ),
        migrations.AlterField(
            model_name="cmsdsfrconfig",
            name="notice_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Standardized consultation link at the end of the notice. Max length: 2000 characters.",
                max_length=2000,
                verbose_name="Notice link",
            ),
        ),
        migrations.AlterField(
            model_name="contentpage",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="For imported pages, to allow updates. Max length: 2000 characters.",
                max_length=2000,
                null=True,
                verbose_name="Source URL",
            ),
        ),
        migrations.AlterField(
            model_name="megamenu",
            name="main_link",
            field=models.URLField(
                blank=True,
                help_text="Max length: 2000 characters.",
                max_length=2000,
                null=True,
                verbose_name="Main link",
            ),
        ),
        migrations.AlterField(
            model_name="socialmediaitem",
            name="url",
            field=models.URLField(
                blank=True, default="", help_text="Max length: 2000 characters.", max_length=2000, verbose_name="URL"
            ),
        ),
    ]
