# Generated by Django 5.2 on 2025-05-21 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_manager", "0057_alter_catalogindexpage_body_alter_contentpage_body"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsdsfrconfig",
            name="operator_logo_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Site logo",
            ),
        ),
    ]
