# Generated by Django 5.2.1 on 2025-05-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0058_cmsdsfrconfig_operator_logo_display_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmsdsfrconfig",
            name="operator_logo_width",
            field=models.DecimalField(
                decimal_places=1,
                default="5.0",
                help_text="To be adjusted according to the width of the logo.            Example for a vertical logo: 3.5, Example for a horizontal logo: 8.",
                max_digits=3,
                null=True,
                verbose_name="Width (em)",
            ),
        ),
    ]
