# Generated by Django 5.2 on 2025-05-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content_manager", "0058_alter_cmsdsfrconfig_operator_logo_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmsdsfrconfig",
            name="operator_logo_display",
            field=models.CharField(
                blank=True,
                choices=[("header-footer", "Header and Footer"), ("header-only", "Header only")],
                default="",
                max_length=20,
                verbose_name="Logo display",
            ),
        ),
    ]
