# Generated by Django 5.2.1 on 2025-05-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0059_auto_20250523_1755"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogindexpage",
            name="header_cta_label",
        ),
        migrations.RemoveField(
            model_name="catalogindexpage",
            name="header_cta_link",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="header_cta_label",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="header_cta_link",
        ),
    ]
