# Generated by Django 5.2.1 on 2025-05-28 14:27

from django.db import migrations
from content_manager.models import ContentPage, CatalogIndexPage
from itertools import chain


def migrate_obsolete_fields(apps, schema_editor):
    pages = chain(ContentPage.objects.all(), CatalogIndexPage.objects.all())

    for live_page in pages:
        if not live_page.header_cta_label and not live_page.header_cta_link:
            continue

        if live_page.header_cta_buttons:
            continue

        page = live_page.get_latest_revision_as_object()
        original_last_published = page.last_published_at

        button_block = (
            "button",
            {
                "text": page.header_cta_label,
                "button_type": "",
                "icon_class": "",
                "icon_side": "",
                "external_url": page.header_cta_link,
            },
        )

        page.header_cta_buttons = [("buttons", [button_block])]

        # Save a revision and publish it
        revision = page.save_revision()

        if live_page.live:
            revision.publish()

        # Reset the last publication date to avoid indexing errors based on this field.
        page.last_published_at = original_last_published
        page.latest_revision_created_at = original_last_published
        page.save(update_fields=["last_published_at", "latest_revision_created_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0060_auto_20250528_1627"),
    ]

    operations = [migrations.RunPython(migrate_obsolete_fields)]
