# Generated by Django 5.2.1 on 2025-05-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0060_auto_20250528_1627"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="catalogindexpage",
            name="header_cta_label",
        ),
        migrations.RemoveField(
            model_name="catalogindexpage",
            name="header_cta_link",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="header_cta_label",
        ),
        migrations.RemoveField(
            model_name="contentpage",
            name="header_cta_link",
        ),
    ]
