# Generated by Django 5.2.3 on 2025-08-21 14:13

from django.db import migrations
from itertools import chain


def migrate_old_hero_in_new_streamfield_hero(apps, schema_editor):
    # Récupération des modèles historiques
    ContentPage = apps.get_model("content_manager", "ContentPage")
    CatalogIndexPage = apps.get_model("content_manager", "CatalogIndexPage")

    # Tous les objets des deux modèles
    pages = chain(ContentPage.objects.all(), CatalogIndexPage.objects.all())

    # Champs à migrer
    hero_fields = [
        "header_image",
        "header_with_title",
        "header_color_class",
        "header_large",
        "header_darken",
        "header_cta_text",
    ]

    for page in pages:
        old_hero_data = {}

        for field in hero_fields:
            value = getattr(page, field, None)
            if value:
                old_hero_data[field] = value

        if getattr(page, "header_cta_buttons", None):
            buttons_data = []
            for block in page.header_cta_buttons:
                if block.block_type == "buttons":
                    for btn in block.value:
                        buttons_data.append(btn.value)
            if buttons_data:
                old_hero_data["buttons"] = buttons_data

        old_hero_data["header_title"] = page.title

        if old_hero_data:
            page.hero = [("old_hero", old_hero_data)]
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0064_alter_catalogindexpage_body_and_more"),
    ]

    operations = [
        migrations.RunPython(
            migrate_old_hero_in_new_streamfield_hero,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
