# Generated by Django 5.2.8 on 2026-01-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0069_alter_catalogindexpage_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customscriptssettings",
            name="use_tarteaucitron",
            field=models.BooleanField(
                default=False,
                help_text='See <a href="https://sites.beta.gouv.fr/documentation/gestion-des-cookies/">Documentation</a>',
                verbose_name="Use Tarteaucitron?",
            ),
        ),
    ]
