# Generated by Django 5.2.8 on 2026-01-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0071_alter_catalogindexpage_body_alter_contentpage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="catalogindexpage",
            name="filter_selection",
            field=models.CharField(
                choices=[("single", "Single filter selection"), ("multiple", "Multiple filters selection")],
                default="single",
                max_length=50,
                verbose_name="Filter selection mode",
            ),
        ),
        migrations.AddField(
            model_name="catalogindexpage",
            name="multiple_filter_operator",
            field=models.CharField(
                choices=[
                    ("OR", "Display results matching at least one of the filters (inclusive OR)"),
                    ("AND", "Display results matching all filters (cumulative AND)"),
                ],
                default="OR",
                max_length=50,
                verbose_name="Logic for multiple filters",
            ),
        ),
    ]
