# Generated by Django 6.0.2 on 2026-02-25 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0072_catalogindexpage_filter_selection_and_more"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalServicesSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "sentry_dsn",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='DSN provided by Sentry. Overrides the <code>SENTRY_DSN</code> environment variable. See <a href="https://docs.sentry.io/product/sentry-basics/dsn-explainer/">Sentry docs</a>.',
                        max_length=500,
                        verbose_name="Sentry DSN",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
                    ),
                ),
            ],
            options={
                "verbose_name": "External services",
            },
        ),
    ]
