# Generated by Django 6.0.3 on 2026-03-20 18:16

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content_manager", "0074_invert_hero_text_position"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmsdsfrconfig",
            name="language_selector_mode",
            field=models.CharField(
                blank=True,
                choices=[("disabled", "Disabled"), ("simple", "Simple"), ("manual", "Manual")],
                default="disabled",
                max_length=20,
                verbose_name="Language selector",
            ),
        ),
        migrations.CreateModel(
            name="LanguageSelectorItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sort_order", models.IntegerField(blank=True, editable=False, null=True)),
                (
                    "language_code",
                    models.CharField(
                        help_text="The language code (examples: fr, de, en)",
                        max_length=10,
                        verbose_name="Language code",
                    ),
                ),
                (
                    "language_name",
                    models.CharField(
                        help_text="The name of the language in said language (examples: Français, Deutsch, English)",
                        max_length=50,
                        verbose_name="Language name",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[("page", "Page"), ("external_url", "External URL")],
                        default="page",
                        help_text="Select the type of link.",
                        verbose_name="Link type",
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Link to an external URL. Use either this or the page.",
                        max_length=2000,
                        verbose_name="External URL",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        blank=True,
                        help_text="Link to a page on this site. Use either this or the external URL.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailcore.page",
                        verbose_name="Page",
                    ),
                ),
                (
                    "site_config",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_selector_items",
                        to="content_manager.cmsdsfrconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language selector item",
                "verbose_name_plural": "Language selector items",
            },
        ),
    ]
