# Generated by Django 5.2.8 on 2026-01-08 15:49

import content_manager.validators
import django.core.validators
import django.db.models.deletion
import re
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterBottomMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "items",
                    wagtail.fields.StreamField(
                        [("link", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("external_url", "External URL"),
                                        ("document", "Document"),
                                    ],
                                    "help_text": "Select the type of link.",
                                    "label": "Link type",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                                    "label": "Page",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Use either this, the external URL or the page parameter.",
                                    "label": "Document",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Use either this, the document or the page parameter.",
                                    "label": "External URL",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "",
                                    "help_text": "Link to an anchor block on the page. Allowed characters: A-Z, a-z, 0-9, - and _.",
                                    "label": "Anchor ID",
                                    "required": False,
                                    "validators": [
                                        django.core.validators.RegexValidator(
                                            re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                            "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                            "invalid",
                                        )
                                    ],
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "",
                                    "help_text": "Extra query parameters at the end of the link, e.g. filtering options.",
                                    "label": "Extra query parameters",
                                    "required": False,
                                    "validators": [content_manager.validators.validate_query_string],
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "If this field is empty, the title of the linked page or document will be used.",
                                    "label": "Link label",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 0),
                                        ("page", 1),
                                        ("document", 2),
                                        ("external_url", 3),
                                        ("anchor", 4),
                                        ("query_string", 5),
                                        ("text", 6),
                                    ]
                                ],
                                {"label": "Link"},
                            ),
                        },
                        verbose_name="Menu items",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footerbottom_menus",
                        to="wagtailcore.site",
                        unique=True,
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer bottom menu",
                "verbose_name_plural": "Footer bottom menus",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
        migrations.CreateModel(
            name="MainMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "items",
                    wagtail.fields.StreamField(
                        [("link", 7), ("submenu", 11), ("megamenu", 19)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("external_url", "External URL"),
                                        ("document", "Document"),
                                    ],
                                    "help_text": "Select the type of link.",
                                    "label": "Link type",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                                    "label": "Page",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Use either this, the external URL or the page parameter.",
                                    "label": "Document",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Use either this, the document or the page parameter.",
                                    "label": "External URL",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "",
                                    "help_text": "Link to an anchor block on the page. Allowed characters: A-Z, a-z, 0-9, - and _.",
                                    "label": "Anchor ID",
                                    "required": False,
                                    "validators": [
                                        django.core.validators.RegexValidator(
                                            re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                            "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                            "invalid",
                                        )
                                    ],
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "",
                                    "help_text": "Extra query parameters at the end of the link, e.g. filtering options.",
                                    "label": "Extra query parameters",
                                    "required": False,
                                    "validators": [content_manager.validators.validate_query_string],
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "If this field is empty, the title of the linked page or document will be used.",
                                    "label": "Link label",
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 0),
                                        ("page", 1),
                                        ("document", 2),
                                        ("external_url", 3),
                                        ("anchor", 4),
                                        ("query_string", 5),
                                        ("text", 6),
                                    ]
                                ],
                                {"label": "Link"},
                            ),
                            8: ("wagtail.blocks.CharBlock", (), {"label": "Submenu label", "required": True}),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 0),
                                        ("page", 1),
                                        ("document", 2),
                                        ("external_url", 3),
                                        ("anchor", 4),
                                        ("query_string", 5),
                                        ("text", 6),
                                    ]
                                ],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.StreamBlock",
                                [[("link", 9)]],
                                {"label": "Links", "max_num": 8, "min_num": 1},
                            ),
                            11: ("wagtail.blocks.StructBlock", [[("label", 8), ("links", 10)]], {"label": "Submenu"}),
                            12: ("wagtail.blocks.CharBlock", (), {"label": "Mega menu label", "required": True}),
                            13: ("wagtail.blocks.CharBlock", (), {"label": "Description", "required": False}),
                            14: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "See the whole section", "label": "Link label"},
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 0),
                                        ("page", 1),
                                        ("document", 2),
                                        ("external_url", 3),
                                        ("anchor", 4),
                                        ("query_string", 5),
                                        ("text", 14),
                                    ]
                                ],
                                {"label": "Main link", "required": False},
                            ),
                            16: ("wagtail.blocks.CharBlock", (), {"label": "Column label", "required": True}),
                            17: ("wagtail.blocks.StructBlock", [[("label", 16), ("links", 10)]], {"label": "Column"}),
                            18: (
                                "wagtail.blocks.StreamBlock",
                                [[("column", 17)]],
                                {"label": "Columns", "max_num": 4, "min_num": 1, "required": True},
                            ),
                            19: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 12), ("description", 13), ("main_link", 15), ("columns", 18)]],
                                {"label": "Mega menu"},
                            ),
                        },
                        verbose_name="Menu items",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_menus",
                        to="wagtailcore.site",
                        unique=True,
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Main menu",
                "verbose_name_plural": "Main menus",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
        migrations.CreateModel(
            name="TopMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "items",
                    wagtail.fields.StreamField(
                        [("link", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("external_url", "External URL"),
                                        ("document", "Document"),
                                    ],
                                    "help_text": "Select the type of link.",
                                    "label": "Link type",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                                    "label": "Page",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Use either this, the external URL or the page parameter.",
                                    "label": "Document",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Use either this, the document or the page parameter.",
                                    "label": "External URL",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "",
                                    "help_text": "Link to an anchor block on the page. Allowed characters: A-Z, a-z, 0-9, - and _.",
                                    "label": "Anchor ID",
                                    "required": False,
                                    "validators": [
                                        django.core.validators.RegexValidator(
                                            re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                            "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                            "invalid",
                                        )
                                    ],
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "default": "",
                                    "help_text": "Extra query parameters at the end of the link, e.g. filtering options.",
                                    "label": "Extra query parameters",
                                    "required": False,
                                    "validators": [content_manager.validators.validate_query_string],
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "If this field is empty, the title of the linked page or document will be used.",
                                    "label": "Link label",
                                    "required": False,
                                },
                            ),
                            7: (
                                "content_manager.blocks.buttons_links.IconPickerBlock",
                                (),
                                {"label": "Icon", "required": False},
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 0),
                                        ("page", 1),
                                        ("document", 2),
                                        ("external_url", 3),
                                        ("anchor", 4),
                                        ("query_string", 5),
                                        ("text", 6),
                                        ("icon_class", 7),
                                    ]
                                ],
                                {"label": "Link"},
                            ),
                        },
                        verbose_name="Menu items",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="top_menus",
                        to="wagtailcore.site",
                        unique=True,
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Top menu",
                "verbose_name_plural": "Top menus",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
