# Generated by Django 5.2.8 on 2025-12-02 18:03

from django.db import migrations


def _get_model(apps, app_label, model_name):
    try:
        return apps.get_model(app_label, model_name)
    except LookupError:
        return None


def _extract_anchor_and_query_params(fragment: str):
    """Helper to extract an anchor and query string from a URL fragment."""
    if "?" in fragment:
        fragment, query_part = fragment.split("?", 1)
    else:
        query_part = ""

    if "#" in fragment:
        _url_part, anchor_part = fragment.split("#", 1)
    else:
        anchor_part = ""

    return anchor_part, query_part


def _move_flatmenu_items_to_streamfield(old_menu, FlatMenuItem, Page):
    """Convert a queryset of wagtailmenus FlatMenuItlem into a list of
    StreamField blocks suitable for the new menus app.
    """
    items = []
    qs = FlatMenuItem.objects.filter(menu=old_menu).order_by("sort_order", "pk")
    for item in qs:
        link_value = {
            "text": item.link_text or "",
            "page": None,
            "external_url": None,
            "anchor": "",
        }

        if getattr(item, "link_page_id", None):
            link_value["link_type"] = "page"
            try:
                page_obj = Page.objects.get(pk=item.link_page_id)
                link_value["page"] = page_obj
                anchor, query_string = _extract_anchor_and_query_params(item.url_append)
                if anchor:
                    link_value["anchor"] = anchor
                if query_string:
                    link_value["query_string"] = f"?{query_string}"
            except Exception:
                link_value["page"] = None
        else:
            link_value["link_type"] = "external_url"
            link_value["external_url"] = item.link_url or None

        items.append(("link", link_value))

    return items


def forwards_move_top_menu(apps, schema_editor):
    """Migrate wagtailmenus FlatMenu with handle 'header_tools' into menus.TopMenu.

    For each FlatMenu with `handle='header_tools'`, create or update a
    `menus.TopMenu` instance for the same `site` and copy items. Each
    wagtailmenus menu item becomes a `("link", {...})` StreamField block
    with keys compatible with the `LinkWithoutLabelBlock` used by the
    `TopMenu` blocks.
    """

    TopMenu = apps.get_model("menus", "TopMenu")
    Page = apps.get_model("wagtailcore", "Page")

    FlatMenu = _get_model(apps, "wagtailmenus", "FlatMenu")
    FlatMenuItem = _get_model(apps, "wagtailmenus", "FlatMenuItem")

    Site = _get_model(apps, "wagtailcore", "Site")

    if not (FlatMenu and FlatMenuItem and TopMenu):
        return

    legacy_top_menus = FlatMenu.objects.filter(handle__exact="header_tools")
    for old_menu in legacy_top_menus:
        try:
            site = Site.objects.get(id=old_menu.site_id)
            root_page = site.root_page
            locale = root_page.locale

            new_menu, _ = TopMenu.objects.get_or_create(site_id=old_menu.site_id, locale=locale)
        except Exception:
            # Skip if creating the target fails for any reason
            continue

        new_menu.items = _move_flatmenu_items_to_streamfield(old_menu, FlatMenuItem, Page)
        new_menu.save()


def backwards_clear_top_menu(apps, schema_editor):
    """Best-effort reverse: clear `TopMenu` items that may have been set."""

    TopMenu = apps.get_model("menus", "TopMenu")
    if not TopMenu:
        return

    for obj in TopMenu.objects.all():
        obj.items = []
        obj.save()


def forwards_move_footer_bottom_menu(apps, schema_editor):
    """Migrate wagtailmenus FlatMenu with handle 'footer' into menus.FooterBottomMenu.

    For each FlatMenu with `handle='footer'`, create or update a
    `menus.FooterBottomMenu` instance for the same `site` and copy items. Each
    wagtailmenus menu item becomes a `("link", {...})` StreamField block²
    with keys compatible with the `LinkWithoutLabelBlock` used by the
    `FooterBottomMenu` blocks.
    """

    FooterBottomMenu = apps.get_model("menus", "FooterBottomMenu")
    Page = apps.get_model("wagtailcore", "Page")

    FlatMenu = _get_model(apps, "wagtailmenus", "FlatMenu")
    FlatMenuItem = _get_model(apps, "wagtailmenus", "FlatMenuItem")

    Site = _get_model(apps, "wagtailcore", "Site")

    if not (FlatMenu and FlatMenuItem and FooterBottomMenu):
        return

    legacy_footer_menus = FlatMenu.objects.filter(handle__exact="footer")
    for old_menu in legacy_footer_menus:
        try:
            site = Site.objects.get(id=old_menu.site_id)
            root_page = site.root_page
            locale = root_page.locale

            new_menu, _ = FooterBottomMenu.objects.get_or_create(site_id=old_menu.site_id, locale=locale)
        except Exception:
            # Skip if creating the target fails for any reason
            continue

        new_menu.items = _move_flatmenu_items_to_streamfield(old_menu, FlatMenuItem, Page)
        new_menu.save()


def backwards_clear_footer_bottom_menu(apps, schema_editor):
    """Best-effort reverse: clear `FooterBottomMenu` items that may have been set."""

    FooterBottomMenu = apps.get_model("menus", "FooterBottomMenu")
    if not FooterBottomMenu:
        return

    for obj in FooterBottomMenu.objects.all():
        obj.items = []
        obj.save()


def _extract_mega_menu(legacy_mega_menu_item, Page, FlatMenuItem):
    """Helper to extract a MegaMenu StreamField block from a
    wagtailmenus LegacyMegaMenuItem instance.
    """
    parent_menu_item = legacy_mega_menu_item.parent_menu_item

    mega_menu_value = {
        "label": parent_menu_item.link_page.title,
        "description": legacy_mega_menu_item.description or "",
        "columns": [],
    }

    if legacy_mega_menu_item.main_link is not None:
        mega_menu_value["main_link"] = {
            "link_type": "external_url",
            "text": "Voir toute la rubrique",
            "external_url": legacy_mega_menu_item.main_link,
        }

    for cat in legacy_mega_menu_item.categories.all().order_by("sort_order", "pk"):
        category = cat.category
        column_value = {
            "label": category.heading,
            "links": [],
        }

        column_value["links"] = _move_flatmenu_items_to_streamfield(category, FlatMenuItem, Page)

        mega_menu_value["columns"].append(("column", column_value))

    return mega_menu_value


def _extract_submenu(item, page_obj, sub_pages):
    """Helper to extract a Submenu StreamField block from a
    wagtailmenus LegacyMainMenuItem instance that allows subnav.
    """

    try:

        if item.link_text:
            label = item.link_text
        else:
            label = page_obj.title

        submenu_value = {
            "label": label,
            "links": [],
        }

        for sub_page in sub_pages:

            link_value = {
                "text": sub_page.title,
                "page": sub_page,
                "external_url": None,
                "anchor": "",
                "link_type": "page",
            }
            submenu_value["links"].append(("link", link_value))

    except Exception:
        pass

    return submenu_value


def forwards_move_main_menu(apps, schema_editor):
    """Migrate wagtailmenus MainMenu into menus.MainMenu.

    It is the most complex, as it can contain submenus, as well as
    MegaMenus.
    """

    NewMainMenu = apps.get_model("menus", "MainMenu")
    Page = apps.get_model("wagtailcore", "Page")
    LegacyMainMenu = _get_model(apps, "wagtailmenus", "MainMenu")
    LegacyMainMenuItem = _get_model(apps, "wagtailmenus", "MainMenuItem")
    FlatMenuItem = _get_model(apps, "wagtailmenus", "FlatMenuItem")

    Site = _get_model(apps, "wagtailcore", "Site")

    if not (NewMainMenu and LegacyMainMenu and LegacyMainMenuItem):
        return

    legacy_main_menus = LegacyMainMenu.objects.all()
    for old_menu in legacy_main_menus:
        try:
            site = Site.objects.get(id=old_menu.site_id)
            root_page = site.root_page
            locale = root_page.locale

            new_menu, _ = NewMainMenu.objects.get_or_create(site_id=old_menu.site_id, locale=locale)
        except Exception:
            # Skip if creating the target fails for any reason
            continue

        items = []
        qs = LegacyMainMenuItem.objects.filter(menu=old_menu).order_by("sort_order", "pk")
        for legacy_menu_item in qs:
            # Check for megamenu
            mega_menu_entry = legacy_menu_item.megamenu_parent_menu_items.first()
            if mega_menu_entry:
                mega_menu = _extract_mega_menu(mega_menu_entry, Page, FlatMenuItem)
                items.append(("megamenu", mega_menu))
                continue

            # Prepare a simple link (internal or external)
            link_value = {
                "text": legacy_menu_item.link_text,
                "page": None,
                "external_url": None,
                "anchor": "",
            }

            if getattr(legacy_menu_item, "link_page_id", None):
                link_value["link_type"] = "page"
                try:
                    page_obj = legacy_menu_item.link_page
                    # Check for submenus
                    # Can't use page_obj.get_children() as we have a "fake" Page model here
                    sub_pages = [
                        p
                        for p in Page.objects.filter(
                            path__startswith=page_obj.path, live=True, show_in_menus=True
                        ).order_by("title")
                        if len(p.path) == len(page_obj.path) + 4  # Direct children only
                    ]  # Should be equivalent to page_obj.get_children().live().in_menu()

                    # Don't make a submenu for the home page
                    if page_obj != root_page and legacy_menu_item.allow_subnav and len(sub_pages) > 0:
                        submenu = _extract_submenu(legacy_menu_item, page_obj, sub_pages)
                        items.append(("submenu", submenu))
                    else:
                        # Normal internal link
                        link_value["page"] = page_obj
                        anchor, query_string = _extract_anchor_and_query_params(legacy_menu_item.url_append)
                        if anchor:
                            link_value["anchor"] = anchor
                        if query_string:
                            link_value["query_string"] = f"?{query_string}"

                        items.append(("link", link_value))

                except Exception:
                    link_value["page"] = None
            else:
                # Normal external link
                link_value["link_type"] = "external_url"
                link_value["external_url"] = legacy_menu_item.link_url or None
                items.append(("link", link_value))

        new_menu.items = items
        new_menu.save()


def backwards_clear_main_menu(apps, schema_editor):
    """Best-effort reverse: clear `MainMenu` items that may have been set."""

    MainMenu = apps.get_model("menus", "MainMenu")
    if not MainMenu:
        return

    for obj in MainMenu.objects.all():
        obj.items = []
        obj.save()


class Migration(migrations.Migration):
    # Manual migration to move the menus from the wagtailmenus app to the new menus app

    dependencies = [
        ("menus", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_move_top_menu, backwards_clear_top_menu),
        migrations.RunPython(forwards_move_footer_bottom_menu, backwards_clear_footer_bottom_menu),
        migrations.RunPython(forwards_move_main_menu, backwards_clear_main_menu),
    ]
