# Generated by Django 5.2.6 on 2025-09-24 09:06

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0001_initial"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topmenu",
            name="items",
            field=wagtail.fields.StreamField(
                [("link", 5)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                            "label": "Page",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.documents.blocks.DocumentChooserBlock",
                        (),
                        {
                            "help_text": "Use either this, the external URL or the page parameter.",
                            "label": "Document",
                            "required": False,
                        },
                    ),
                    2: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Use either this, the document or the page parameter.",
                            "label": "External URL",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "If this field is empty, the title of the linked page or document will be used.",
                            "label": "Link label",
                            "required": False,
                        },
                    ),
                    4: ("content_manager.blocks.IconPickerBlock", (), {"label": "Icon", "required": False}),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("page", 0), ("document", 1), ("external_url", 2), ("text", 3), ("icon_class", 4)]],
                        {"label": "Link"},
                    ),
                },
                verbose_name="Menu items",
            ),
        ),
        migrations.CreateModel(
            name="FooterBottomMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "items",
                    wagtail.fields.StreamField(
                        [("link", 4)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                                    "label": "Page",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Use either this, the external URL or the page parameter.",
                                    "label": "Document",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Use either this, the document or the page parameter.",
                                    "label": "External URL",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "If this field is empty, the title of the linked page or document will be used.",
                                    "label": "Link label",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("document", 1), ("external_url", 2), ("text", 3)]],
                                {"label": "Link"},
                            ),
                        },
                        verbose_name="Menu items",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footerbottom_menus",
                        to="wagtailcore.site",
                        unique=True,
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer bottom menu",
                "verbose_name_plural": "Footer bottom menus",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
