# Generated by Django 5.2.6 on 2025-09-25 16:41

import django.db.models.deletion
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_alter_topmenu_items_footerbottommenu"),
        ("wagtailcore", "0095_groupsitepermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerbottommenu",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footerbottom_menus",
                to="wagtailcore.site",
                unique=True,
                verbose_name="Site",
            ),
        ),
        migrations.CreateModel(
            name="MainMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("translation_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "items",
                    wagtail.fields.StreamField(
                        [("link", 4), ("submenu", 7)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Link to a page of this site. Use either this, the document, or the external URL parameter.",
                                    "label": "Page",
                                    "required": False,
                                },
                            ),
                            1: (
                                "wagtail.documents.blocks.DocumentChooserBlock",
                                (),
                                {
                                    "help_text": "Use either this, the external URL or the page parameter.",
                                    "label": "Document",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Use either this, the document or the page parameter.",
                                    "label": "External URL",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "If this field is empty, the title of the linked page or document will be used.",
                                    "label": "Link label",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("document", 1), ("external_url", 2), ("text", 3)]],
                                {"label": "Link"},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "If this field is empty, the title of the linked page or document will be used.",
                                    "label": "Link label",
                                    "required": True,
                                },
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("document", 1), ("external_url", 2), ("text", 3)]],
                                {"label": "Link", "max_num": 15, "min_num": 1},
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("page", 0), ("document", 1), ("external_url", 2), ("text", 5), ("links", 6)]],
                                {"label": "Submenu"},
                            ),
                        },
                        verbose_name="Menu items",
                    ),
                ),
                (
                    "locale",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="wagtailcore.locale",
                        verbose_name="locale",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="main_menus",
                        to="wagtailcore.site",
                        unique=True,
                        verbose_name="Site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer bottom menu",
                "verbose_name_plural": "Footer bottom menus",
                "abstract": False,
                "unique_together": {("translation_key", "locale")},
            },
        ),
    ]
