# Generated by Django 6.0.3 on 2026-03-19 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_migrate_from_legacy_menus"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="footerbottommenu",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="mainmenu",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="topmenu",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AlterField(
            model_name="footerbottommenu",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site", verbose_name="Site"
            ),
        ),
        migrations.AlterField(
            model_name="mainmenu",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site", verbose_name="Site"
            ),
        ),
        migrations.AlterField(
            model_name="topmenu",
            name="site",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site", verbose_name="Site"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="footerbottommenu",
            unique_together={("site", "locale"), ("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="mainmenu",
            unique_together={("site", "locale"), ("translation_key", "locale")},
        ),
        migrations.AlterUniqueTogether(
            name="topmenu",
            unique_together={("site", "locale"), ("translation_key", "locale")},
        ),
    ]
