# Generated by Django 6.0.3 on 2026-03-24 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menus", "0002_migrate_from_legacy_menus"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footerbottommenu",
            name="site",
            field=models.OneToOneField(
                editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
            ),
        ),
        migrations.AlterField(
            model_name="mainmenu",
            name="site",
            field=models.OneToOneField(
                editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
            ),
        ),
        migrations.AlterField(
            model_name="topmenu",
            name="site",
            field=models.OneToOneField(
                editable=False, on_delete=django.db.models.deletion.CASCADE, to="wagtailcore.site"
            ),
        ),
    ]
