# Generated by Django 4.1.10 on 2023-09-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0078_referenceindex"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormationPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Intitulé")),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[("formation", "Formation"), ("parcours", "Parcours")],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("short_description", models.TextField(blank=True, verbose_name="Descriptif court")),
                ("knowledge_at_the_end", models.TextField(blank=True, verbose_name="À la fin, vous saurez")),
                ("duration", models.IntegerField(blank=True, null=True, verbose_name="Durée (min)")),
                ("registration_link", models.URLField(blank=True, max_length=255, verbose_name="Lien d'inscription")),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
