# Generated by Django 4.1.10 on 2023-11-17 19:46

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organizer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("airtable_id", models.CharField(max_length=255, verbose_name="Identifiant Airtable")),
            ],
            options={
                "verbose_name": "Entité organisatrice",
                "verbose_name_plural": "Entités organisatrices",
            },
        ),
        migrations.CreateModel(
            name="TargetAudience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Public cible",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Theme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
                ("airtable_id", models.CharField(max_length=255, verbose_name="Identifiant Airtable")),
            ],
            options={
                "verbose_name": "Famille thématique",
                "verbose_name_plural": "Familles thématiques",
            },
        ),
        migrations.AddField(
            model_name="formationpage",
            name="organizers",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="formations.organizer", verbose_name="Entités organisatrices"
            ),
        ),
        migrations.AddField(
            model_name="formationpage",
            name="target_audience",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="formations.targetaudience", verbose_name="Public cible"
            ),
        ),
        migrations.AddField(
            model_name="formationpage",
            name="themes",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="formations.theme", verbose_name="Familles thématiques"
            ),
        ),
    ]
