# Generated by Django 4.1.10 on 2023-11-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0002_organizer_targetaudience_theme_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formationpage",
            name="duration",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Durée (min)"),
        ),
    ]
