# Generated by Django 4.1.10 on 2023-12-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("formations", "0003_alter_formationpage_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="formationpage",
            name="attendance",
            field=models.CharField(
                blank=True,
                choices=[("enligne", "En ligne"), ("présentiel", "Présentiel"), ("hybride", "Hybride")],
                max_length=20,
                verbose_name="En ligne/Présentiel/Hybride",
            ),
        ),
    ]
