# Generated by Django 5.2.1 on 2025-06-09 09:06

import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0004_formationpage_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubTheme",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Sous-thématique",
                "verbose_name_plural": "Sous-thématiques",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="formationpage",
            name="sub_themes",
            field=modelcluster.fields.ParentalManyToManyField(
                blank=True, to="formations.subtheme", verbose_name="Sous-thématiques"
            ),
        ),
    ]
