# Generated by Django 5.2.1 on 2025-07-02 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("formations", "0005_subtheme_formationpage_sub_themes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formationpage",
            name="registration_link",
            field=models.CharField(blank=True, max_length=255, verbose_name="Lien d'inscription"),
        ),
    ]
